require "../helper"

describe Twitter::User do
  describe ".from_json" do
    it "parses all attributes correctly" do
      json = JSON.parse(File.read("./spec/fixtures/users.json"))[0].to_json
      user = Twitter::User.from_json(json)
      user.contributors_enabled.should eq(false)
      user.created_at.should eq(Time.parse!("Mon Jul 16 12:59:01 +0000 2007", "%a %b %d %T %z %Y"))
      user.default_profile.should eq(false)
      user.default_profile_image.should eq(false)
      user.favourites_count.should eq(14447)
      user.follow_request_sent.should eq(false)
      user.followers_count.should eq(5945)
      user.following.should eq(false)
      user.friends_count.should eq(881)
      user.geo_enabled.should eq(true)
      user.id.should eq(7505382)
      user.is_translation_enabled.should eq(false)
      user.is_translator.should eq(false)
      user.lang.should eq("en")
      user.listed_count.should eq(339)
      user.location.should eq("Berlin")
      user.name.should eq("Erik Michaels-Ober")
      user.needs_phone_verification.should eq(false)
      user.notifications.should eq(false)
      user.profile_background_color.should eq("000000")
      user.profile_background_image_url.should eq("http://pbs.twimg.com/profile_background_images/677717672/bb0b3653dcf0644e344823e0a2eb3382.png")
      user.profile_background_image_url_https.should eq("https://pbs.twimg.com/profile_background_images/677717672/bb0b3653dcf0644e344823e0a2eb3382.png")
      user.profile_background_tile.should eq(false)
      user.profile_banner_url.should eq("https://pbs.twimg.com/profile_banners/7505382/1425238640")
      user.profile_image_url.should eq("http://pbs.twimg.com/profile_images/583426225605058560/dO_rpWw1_normal.jpg")
      user.profile_image_url_https.should eq("https://pbs.twimg.com/profile_images/583426225605058560/dO_rpWw1_normal.jpg")
      user.profile_link_color.should eq("393740")
      user.profile_location.should eq(nil)
      user.profile_sidebar_border_color.should eq("000000")
      user.profile_sidebar_fill_color.should eq("DDEEF6")
      user.profile_text_color.should eq("333333")
      user.profile_use_background_image.should eq(true)
      user.protected.should eq(false)
      user.screen_name.should eq("sferik")
      user.status.should be_a(Twitter::Tweet)
      user.statuses_count.should eq(17358)
      user.suspended.should eq(false)
      user.time_zone.should eq("Berlin")
      user.url.should eq("https://t.co/L2xIBazeZH")
      user.utc_offset.should eq(7200)
      user.verified.should eq(false)
    end
  end
end
